name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master" ]
    paths-ignore:
      - '**/README.md'

# Builds images for target boards.
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16.x]
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.JS ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
      - name: Update yarn and npm
        run: npm i -g npm
      - name: Install and build chonky
        run: cd ./packages/chonky && npm install && npm run build
